services:
    mowlkky.controller.back.index:
        class: Wanimo\Mowlkky\BackBundle\Controller\IndexController
        arguments: ['@templating']

    mowlkky.controller.back.login:
        class: Wanimo\Mowlkky\BackBundle\Controller\LoginController
        arguments: ['@templating', '@security.authentication_utils']

    # Tournaments management
    mowlkky.controller.back.tournament.index:
        class: Wanimo\Mowlkky\BackBundle\Controller\Tournament\IndexController
        arguments: ['@templating', '@mowlkky.repository.tournament']